keys:
  key1: TESTCODEONE
  key2: TESTCODETWO

message: "Dear Max, How are you doing? I myself am doing well. sincerely, Daniel"

keymasks:
  key1:
    "1111111111111111111111111111111111111111111111111111111111111111      "
  key2:
    "111111111                                                             "

